//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Client.ServiceReference_WSHttp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_WSHttp.ITimviec")]
    public interface ITimviec {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimviec/GetAuthors", ReplyAction="http://tempuri.org/ITimviec/GetAuthorsResponse")]
        string GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITimviec/GetAuthors", ReplyAction="http://tempuri.org/ITimviec/GetAuthorsResponse")]
        System.IAsyncResult BeginGetAuthors(System.AsyncCallback callback, object asyncState);
        
        string EndGetAuthors(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimviec/Detai", ReplyAction="http://tempuri.org/ITimviec/DetaiResponse")]
        string Detai();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITimviec/Detai", ReplyAction="http://tempuri.org/ITimviec/DetaiResponse")]
        System.IAsyncResult BeginDetai(System.AsyncCallback callback, object asyncState);
        
        string EndDetai(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimviecChannel : Form_Client.ServiceReference_WSHttp.ITimviec, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DetaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimviecClient : System.ServiceModel.ClientBase<Form_Client.ServiceReference_WSHttp.ITimviec>, Form_Client.ServiceReference_WSHttp.ITimviec {
        
        private BeginOperationDelegate onBeginGetAuthorsDelegate;
        
        private EndOperationDelegate onEndGetAuthorsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthorsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDetaiDelegate;
        
        private EndOperationDelegate onEndDetaiDelegate;
        
        private System.Threading.SendOrPostCallback onDetaiCompletedDelegate;
        
        public TimviecClient() {
        }
        
        public TimviecClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimviecClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimviecClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimviecClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAuthorsCompletedEventArgs> GetAuthorsCompleted;
        
        public event System.EventHandler<DetaiCompletedEventArgs> DetaiCompleted;
        
        public string GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthors(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthors(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetAuthors(System.IAsyncResult result) {
            return base.Channel.EndGetAuthors(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthors(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAuthors(callback, asyncState);
        }
        
        private object[] OnEndGetAuthors(System.IAsyncResult result) {
            string retVal = this.EndGetAuthors(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthorsCompleted(object state) {
            if ((this.GetAuthorsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthorsCompleted(this, new GetAuthorsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthorsAsync() {
            this.GetAuthorsAsync(null);
        }
        
        public void GetAuthorsAsync(object userState) {
            if ((this.onBeginGetAuthorsDelegate == null)) {
                this.onBeginGetAuthorsDelegate = new BeginOperationDelegate(this.OnBeginGetAuthors);
            }
            if ((this.onEndGetAuthorsDelegate == null)) {
                this.onEndGetAuthorsDelegate = new EndOperationDelegate(this.OnEndGetAuthors);
            }
            if ((this.onGetAuthorsCompletedDelegate == null)) {
                this.onGetAuthorsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthorsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthorsDelegate, null, this.onEndGetAuthorsDelegate, this.onGetAuthorsCompletedDelegate, userState);
        }
        
        public string Detai() {
            return base.Channel.Detai();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDetai(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDetai(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndDetai(System.IAsyncResult result) {
            return base.Channel.EndDetai(result);
        }
        
        private System.IAsyncResult OnBeginDetai(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDetai(callback, asyncState);
        }
        
        private object[] OnEndDetai(System.IAsyncResult result) {
            string retVal = this.EndDetai(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDetaiCompleted(object state) {
            if ((this.DetaiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DetaiCompleted(this, new DetaiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DetaiAsync() {
            this.DetaiAsync(null);
        }
        
        public void DetaiAsync(object userState) {
            if ((this.onBeginDetaiDelegate == null)) {
                this.onBeginDetaiDelegate = new BeginOperationDelegate(this.OnBeginDetai);
            }
            if ((this.onEndDetaiDelegate == null)) {
                this.onEndDetaiDelegate = new EndOperationDelegate(this.OnEndDetai);
            }
            if ((this.onDetaiCompletedDelegate == null)) {
                this.onDetaiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDetaiCompleted);
            }
            base.InvokeAsync(this.onBeginDetaiDelegate, null, this.onEndDetaiDelegate, this.onDetaiCompletedDelegate, userState);
        }
    }
}
